name: Update Readme

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4,8,12,16,20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up version PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Run PHP script
        env:
          API_WEATHER_KEY: ${{ secrets.API_WEATHER_KEY }}
        run: php update-readme.php
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "trungdv@fabbi.io"
          git config --global user.name "trungdv-fabbi"
          git commit -m "docs: update greeting and quote" -a || echo "No changes to commit"
          git push

permissions:
  contents: write
